# Custom Language File for AAKS Launcher

[ejs.app]
title = "AAKS Launcher"

[ejs.landing]
#mediaGitHubURL = "https://github.com/aleshyy/aakslauncher"
mediaWebURL = "https://aaks.aleshy.net"
mediaDiscordURL = "https://discord.gg/cf7fj6yWtz"

[ejs.settings]
#sourceGithubLink = "https://github.com/aleshyy/aakslauncher"
supportLink = "https://aaks.aleshy.net/soporte/"

#[ejs.welcome]
#welcomeHeader = "Hola, esto es AAKS Launcher"
#welcomeDescription = "Nuestra misión es crear una experiencia única, facilitando el acceso a nuestros servidores de Minecraft."
#welcomeDescCTA = "Estás a solo unos clics de entrar al paraíso AAKS Launcher."
